### ISSUE TITLE
Please publish this as a crate on crates.io

### ISSUE THREAD

**Issue by Jasper-Bekkers** [yzsolt/meshopt-rs#5]
I'm trying to use this crate for some initial experiments and later I'd love to switch over to it fully. Doing the experiments on a git dependency is fine for now but I'd love to see a proper crates.io release at some point if that's possible.

Thanks for taking the time to build this out, having meshopt as a native Rust crate is real nice!

**Comment by yzsolt** [comment]
Sorry for the late reply, somehow I missed the notification about this issue... Publishing on crates.io is definitely planned! I wanted to finish the benchmarking suite first, but it's not a hard requirement I guess. I'll prepare the first release and publish it next week!

**Comment by yzsolt** [comment]
`meshopt-rs` v0.1.0 is now available at [crates.io](https://crates.io/crates/meshopt-rs)! 🥳
